// Evidence Pack builder — workspace-scoped, server-side only
import { listActions } from "@/server/actionsStore";
import { readAuditLog } from "@/server/auditLog";
import type { ActionDraft, AuditEntry, PackType } from "@/modules/actions/types";
import { DEFAULT_WORKSPACE } from "@/modules/actions/types";

export interface EvidenceBundle {
    packId: string;
    workspaceId: string;
    packType: PackType;
    input: Record<string, unknown>;
    output: Record<string, unknown>;
    actions: ActionDraft[];
    audit: AuditEntry[];
    createdAt: string;
}

export function buildEvidencePack(
    packId: string,
    packType: PackType,
    input: Record<string, unknown>,
    output: Record<string, unknown>,
    workspaceId: string = DEFAULT_WORKSPACE
): EvidenceBundle {
    return {
        packId,
        workspaceId,
        packType,
        input,
        output,
        actions: listActions({ packId, workspaceId }),
        audit: readAuditLog(packId, workspaceId),
        createdAt: new Date().toISOString(),
    };
}

export function toEvidenceIndexMarkdown(bundle: EvidenceBundle): string {
    const inp = bundle.input as { industry?: string; offer?: string; goal7d?: string };
    const actionRows = bundle.actions.map(a =>
        `| ${a.id.slice(-8)} | ${a.type} | ${a.status} | ${a.riskLevel} |`
    ).join("\n");

    const eventCounts: Record<string, number> = {};
    for (const e of bundle.audit) {
        eventCounts[e.event] = (eventCounts[e.event] || 0) + 1;
    }
    const auditSummary = Object.entries(eventCounts).map(([k, v]) => `- ${k}: ${v}`).join("\n");

    // ERPNext results section
    const erpSection = (() => {
        const erpActions = bundle.actions.filter(a => a.status === "executed" && a.result && (a.result as Record<string, unknown>).provider === "erpnext");
        if (erpActions.length === 0) return "No ERPNext executions recorded.";
        return erpActions.map(a => {
            const res = a.result as { created?: { doctype: string; name: string; url: string }[] };
            const docs = res.created?.map(c => `  - [${c.doctype}: ${c.name}](${c.url})`).join("\n") || "  - No documents created";
            return `### ${a.type}\n${docs}`;
        }).join("\n\n");
    })();

    return `# Evidence Pack — ${bundle.packType.toUpperCase()}

**Pack ID:** ${bundle.packId}
**Workspace:** ${bundle.workspaceId}
**Created:** ${bundle.createdAt}
**Type:** ${bundle.packType}

## Pack Summary
- **Industry:** ${inp.industry || "N/A"}
- **Offer:** ${inp.offer || "N/A"}
- **Goal 7d:** ${inp.goal7d || "N/A"}

## Files
| File | Description |
|------|-------------|
| input.json | Sprint Pack inputs |
| output.json | Validated pack output |
| output.md | Human-readable output |
| actions.json | Action drafts + statuses |
| audit.jsonl | Full audit trail |
| erpnext_results.json | ERPNext execution results (if any) |
| evidence.md | This file |

## Actions
| ID | Type | Status | Risk |
|----|------|--------|------|
${actionRows || "| — | No actions created | — | — |"}

## Audit Trail
${auditSummary || "No audit events recorded."}

## Next Actions
${bundle.actions.filter(a => a.status === "draft").map(a => `- [ ] ${a.type} (${a.riskLevel})`).join("\n") || "All actions processed."}

## ERPNext Execution Results
${erpSection}

---
*Generated by BusinessOS Sprint Pack*
`;
}

export function buildEvidenceFiles(bundle: EvidenceBundle, outputMd: string): { name: string; content: string }[] {
    const erpResults = bundle.actions
        .filter(a => a.status === "executed" && a.result && (a.result as Record<string, unknown>).provider === "erpnext")
        .map(a => ({ actionId: a.id, type: a.type, result: a.result }));

    return [
        { name: "input.json", content: JSON.stringify(bundle.input, null, 2) },
        { name: "output.json", content: JSON.stringify(bundle.output, null, 2) },
        { name: "output.md", content: outputMd },
        { name: "actions.json", content: JSON.stringify(bundle.actions, null, 2) },
        { name: "audit.jsonl", content: bundle.audit.map(e => JSON.stringify(e)).join("\n") },
        { name: "erpnext_results.json", content: JSON.stringify(erpResults, null, 2) },
        { name: "evidence.md", content: toEvidenceIndexMarkdown(bundle) },
    ];
}

// Workspace-scoped output directory
export function evidenceDir(workspaceId: string, packId: string): string {
    return `data/evidence/${workspaceId}/${packId}`;
}
